### ISSUE TITLE
Disconnection issue

### ISSUE THREAD

**Issue by SeijiTataki** [nvb-uy/Shield_Overhaul#20]
Running a Fabric 0.15.0 server with Shield Overhaul 1.0.3, with Parrying currently disabled.

Intermittently, players are getting disconnected with the following error:

Internal Exception: java.lang.NullPointerException: Cannot invoke "elocindev.shield_overhaul.util.IShieldAnimatedPlayer.shield_overhaul_getModAnimation()" because "user" is null

Am attempting to get players to send me their log file to help troubleshoot. All players affected by this disconnect are not using shields while playing.

Excerpt from one user's log:

[03:39:31] [Render thread/INFO]: [System] [CHAT] [LD] You died at 276, 66, 9, in minecraft:overworld.
[03:39:33] [Netty Client IO #1/INFO]: Unloading client level [Wrapped{ClientLevel@overworld}].
[03:39:33] [Netty Client IO #1/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientLevel@4cef0a55
[03:39:33] [Netty Client IO #1/INFO]: Shutting down ClientRenderState
[03:39:33] [Netty Client IO #1/INFO]: Shutting down LodRenderer...
[03:39:33] [Netty Client IO #1/INFO]: Queuing Renderer Cleanup for main render thread
[03:39:33] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Started
[03:39:33] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Complete
[03:39:33] [Netty Client IO #1/INFO]: Finished shutting down LodRenderer
[03:39:33] [Netty Client IO #1/INFO]: Shutting down LodQuadTree...
[03:39:33] [Render thread/INFO]: Default Sub Dimension not found. Creating: [overworld]
[03:39:33] [Render thread/INFO]: Started DHLevel for Wrapped{ClientLevel@overworld} with saves at [ClientOnlySaveStructure@Bistro+Craft]
[03:39:33] [Render thread/INFO]: Setting up renderer
[03:39:33] [Render thread/INFO]: Loading shader with type: 35633
[03:39:33] [Render thread/INFO]: Shader loaded sucessfully.
[03:39:33] [Render thread/INFO]: Loading shader with type: 35632
[03:39:33] [Render thread/INFO]: Shader loaded sucessfully.
[03:39:33] [Netty Client IO #1/INFO]: Finished shutting down LodQuadTree
[03:39:33] [Netty Client IO #1/INFO]: Closing RenderSourceFileHandler with [581] files...
[03:39:33] [Netty Client IO #1/INFO]: Closed DhClientLevel for Wrapped{ClientLevel@overworld}
[03:39:33] [Render thread/INFO]: Vertex Attribute (GL43+) completed. It contains 1 binding points and a stride size of 12
[03:39:33] [Render thread/INFO]: Quad IBO Resizing from [0] to [21845] with type: GL_UNKNOWN(5125)
[03:39:33] [Render thread/INFO]: Renderer setup complete
[03:39:33] [Render thread/INFO]: Unloading client level [Wrapped{ClientLevel@overworld}].
[03:39:33] [Render thread/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientLevel@5e113d4c
[03:39:33] [Render thread/INFO]: Shutting down ClientRenderState
[03:39:33] [Render thread/INFO]: Shutting down LodRenderer...
[03:39:33] [Render thread/INFO]: Queuing Renderer Cleanup for main render thread
[03:39:33] [Render thread/INFO]: Finished shutting down LodRenderer
[03:39:33] [Render thread/INFO]: Shutting down LodQuadTree...
[03:39:33] [Render thread/INFO]: Finished shutting down LodQuadTree
[03:39:33] [Render thread/INFO]: Closing RenderSourceFileHandler with [0] files...
[03:39:33] [Render thread/INFO]: Closed DhClientLevel for Wrapped{ClientLevel@overworld}
[03:39:33] [Render thread/INFO]: Loading  client level [Wrapped{ClientLevel@overworld}].
[03:39:33] [Render thread/INFO]: Default Sub Dimension not found. Creating: [overworld]
[03:39:33] [Render thread/INFO]: Started DHLevel for Wrapped{ClientLevel@overworld} with saves at [ClientOnlySaveStructure@Bistro+Craft]
[03:39:33] [Render thread/INFO]: Loaded [0] waiting chunk wrappers.
[03:39:33] [Render thread/INFO]: Minimap updated server level id: 1400290533 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[03:39:33] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Started
[03:39:33] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Complete
[03:39:33] [Render thread/INFO]: Setting up renderer
[03:39:33] [Render thread/INFO]: Loading shader with type: 35633
[03:39:33] [Render thread/INFO]: Shader loaded sucessfully.
[03:39:33] [Render thread/INFO]: Loading shader with type: 35632
[03:39:33] [Render thread/INFO]: Shader loaded sucessfully.
[03:39:33] [Render thread/INFO]: Vertex Attribute (GL43+) completed. It contains 1 binding points and a stride size of 12
[03:39:33] [Render thread/INFO]: Quad IBO Resizing from [0] to [21845] with type: GL_UNKNOWN(5125)
[03:39:33] [Render thread/INFO]: Renderer setup complete
[03:40:00] [Render thread/INFO]: Loaded 595 advancements
[03:40:41] [Render thread/INFO]: Loaded 596 advancements
[03:40:59] [DH-LOD Builder - Light Populator Thread[1]/ERROR]: Unexpected lighting issue for center chunk: C[-1,1]
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 0
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.chunk.ChunkWrapper.lambda$getBlockLightPosList$1(ChunkWrapper.java:394) ~[DistantHorizons-2.0.1-a-1.20.1.jar:?]
	at net.minecraft.class_2791.method_51525(class_2791.java:322) ~[client-intermediary.jar:?]
	at net.minecraft.class_2791.method_51524(class_2791.java:306) ~[client-intermediary.jar:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.chunk.ChunkWrapper.getBlockLightPosList(ChunkWrapper.java:392) ~[DistantHorizons-2.0.1-a-1.20.1.jar:?]
	at com.seibel.distanthorizons.core.generation.DhLightingEngine.lightChunk(DhLightingEngine.java:122) ~[DistantHorizons-2.0.1-a-1.20.1.jar:?]
	at com.seibel.distanthorizons.core.api.internal.SharedApi.lambda$bakeChunkLightingAndSendToLevelAsync$0(SharedApi.java:285) ~[DistantHorizons-2.0.1-a-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:43:58] [Netty Client IO #1/ERROR]: Encountered exception while handling in channel with name "shield_overhaul:shield_bash_animation_packet"
java.lang.NullPointerException: Cannot invoke "elocindev.shield_overhaul.util.IShieldAnimatedPlayer.shield_overhaul_getModAnimation()" because "user" is null
	at elocindev.shield_overhaul.util.ShieldAnimationUtils.playShieldBash(ShieldAnimationUtils.java:16) ~[Shield_Overhaul-FABRIC-MC1.20.1-1.0.3.jar:?]
	at elocindev.shield_overhaul.networking.ShieldBashAnimationS2CPacket.receive(ShieldBashAnimationS2CPacket.java:15) ~[Shield_Overhaul-FABRIC-MC1.20.1-1.0.3.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.minecraft.class_634.handler$dcj000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3268) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:43:58] [Netty Client IO #1/ERROR]: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "elocindev.shield_overhaul.util.IShieldAnimatedPlayer.shield_overhaul_getModAnimation()" because "user" is null
	at elocindev.shield_overhaul.util.ShieldAnimationUtils.playShieldBash(ShieldAnimationUtils.java:16) ~[Shield_Overhaul-FABRIC-MC1.20.1-1.0.3.jar:?]
	at elocindev.shield_overhaul.networking.ShieldBashAnimationS2CPacket.receive(ShieldBashAnimationS2CPacket.java:15) ~[Shield_Overhaul-FABRIC-MC1.20.1-1.0.3.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
	at net.minecraft.class_634.handler$dcj000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3268) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:43:58] [Netty Client IO #1/INFO]: Unloading synced configs from server
[03:43:58] [Netty Client IO #1/INFO]: [Fabric Seasons] Left dedicated server, restoring config.
[03:43:58] [Render thread/INFO]: [voicechat] Clearing audio channels
[03:43:58] [Render thread/INFO]: [voicechat] Closing audio channel for f8baa032-7acd-4597-85d2-8ee6e94225e4
[03:43:58] [AudioChannelThread-f8baa032-7acd-4597-85d2-8ee6e94225e4/INFO]: [voicechat] Closed audio channel for f8baa032-7acd-4597-85d2-8ee6e94225e4
[03:43:58] [Render thread/INFO]: [voicechat] Stopping microphone thread
[03:43:58] [Render thread/INFO]: [voicechat] Disconnecting voicechat
[03:43:58] [Render thread/INFO]: Clearing unused audio channels
[03:43:58] [Render thread/INFO]: Unloading client level [Wrapped{ClientLevel@overworld}].
[03:43:58] [Render thread/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientLevel@7c117aae
[03:43:58] [Render thread/INFO]: Shutting down ClientRenderState
[03:43:58] [Render thread/INFO]: Shutting down LodRenderer...
[03:43:58] [Render thread/INFO]: Queuing Renderer Cleanup for main render thread
[03:43:58] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Started
[03:43:58] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Complete
[03:43:58] [Render thread/INFO]: Finished shutting down LodRenderer
[03:43:58] [Render thread/INFO]: Shutting down LodQuadTree...
[03:43:58] [Render thread/INFO]: Finished shutting down LodQuadTree
[03:43:58] [Render thread/INFO]: Closing RenderSourceFileHandler with [387] files...
[03:43:58] [Render thread/INFO]: Closed DhClientLevel for Wrapped{ClientLevel@overworld}
[03:43:58] [Render thread/INFO]: Client on ClientOnly mode disconnecting.
[03:43:58] [Render thread/INFO]: Closed DhWorld of type Client_Only
[03:43:59] [Render thread/INFO]: Minimap session finalized.
[03:43:59] [Render thread/INFO]: Finalizing world map session...
[03:43:59] [Thread-25/INFO]: World map force-cleaned!
[03:43:59] [Render thread/INFO]: World map session finalized.
[03:43:59] [Render thread/INFO]: Stopping JEI
[03:43:59] [Render thread/INFO]: Stopping JEI
[03:43:59] [Render thread/INFO]: Sending Runtime Unavailable...
[03:43:59] [Render thread/INFO]: Stopping JEI GUI
[03:43:59] [Render thread/INFO]: Sending Runtime Unavailable took 472.8 ?s
[03:43:59] [Render thread/INFO]: Stopping worker threads
[03:44:36] [Render thread/INFO]: Stopping JEI
[03:44:36] [Render thread/INFO]: Stopping JEI
[03:44:36] [Render thread/INFO]: Sending Runtime Unavailable...
[03:44:36] [Render thread/INFO]: Stopping JEI GUI
[03:44:36] [Render thread/INFO]: Sending Runtime Unavailable took 441.8 ?s

**Comment by nvb-uy** [comment]
@JRepo42

**Comment by SeijiTataki** [comment]
This happened again to two other players. They were ~200 blocks away from someone actively using a shield to bash while they were not engaged in combat.

**Comment by KNaiFen** [comment]
I also met this situation, exactly the same

**Comment by JRepo42** [comment]
> This happened again to two other players. They were ~200 blocks away from someone actively using a shield to bash while they were not engaged in combat.
Sorry for the late reply; I've been working on (ironically) an overhaul update for this mod which reworked quite a few things, and I will add this to the list of things to ensure is patched.

> I also met this situation, exactly the same
Thanks for the report, see the above :)

**Comment by rxay579** [comment]
Same issue noted in recently put together mod list on a local server.
Shield bashing causes another nearby player to be kicked out.
Minecraft v1.20.1, Fabric Loader v0.15.7, Fabric API 0.92.0.
Full list uploaded as modlist.txt, log snippet as logsnippet.txt.
More details available if needed.

[modlist.txt](https://github.com/nvb-uy/Shield_Overhaul/files/14662260/modlist.txt)
[logsnippet.txt](https://github.com/nvb-uy/Shield_Overhaul/files/14662261/logsnippet.txt)
